version: '3.7'

services:
  naming-server:
    image: tanackovicit35/2023-naming-server:latest
	mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
	  
  users-service:
    image: tanackovicit35/2023-users-service:latest
	mem_limit: 700m
    ports:
      - "8770:8770"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
	  
  bank-account:
    image: tanackovicit35/2023-bank-account:latest
	mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
	  
  currency-exchange:
    image: tanackovicit35/2023-currency-exchange:latest
	mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
	  
  currency-conversion:
    image: tanackovicit35/2023-currency-conversion:latest
	mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	  - bank-account
	  - currency-exchange
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
	    
  crypto-wallet:
    image: tanackovicit35/2023-crypto-wallet:latest
	mem_limit: 700m
    ports:
      - "8300:8300"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  crypto-exchange:
    image: tanackovicit35/2023-crypto-exchange:latest
	mem_limit: 700m
    ports:
      - "8400:8400"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
	  
  crypto-conversion:
    image: tanackovicit35/2023-crypto-conversion:latest
	mem_limit: 700m
    ports:
      - "8500:8500"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	  - crypto-exchange
	  - crypto-wallet
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
	  
  trade-service:
    image: tanackovicit35/2023-trade-service:latest
	mem_limit: 700m
    ports:
      - "8600:8600"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	  - bank-account
	  - crypto-wallet
	  - currency-exchange
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
	  
  api-gateway:
    image: tanackovicit35/2023-api-gateway:latest
	mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
	depends_on:
	  - naming-server
	  - users-service
	  - bank-account
	  - currency-exchange
	  - currency-conversion
	  - crypto-wallet
	  - crypto-exchange
	  - crypto-conversion
	  - trade-service
	environment:
	  EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

networks:
  currency-network: